export enum EAuthority {

  ADMIN_DASHBOARD = 'ADMIN_DASHBOARD',
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  ADD_USER = 'ADD_USER',
  EDIT_USER = 'EDIT_USER',
  CHANGE_USER_STATUS = 'CHANGE_USER_STATUS',
  RESET_PASSWORD = 'RESET_PASSWORD',
  DELETE_USER = 'DELETE_USER',
  ROLE_MANAGEMENT = 'ROLE_MANAGEMENT',
  ADD_ROLE = 'ADD_ROLE',
  EDIT_ROLE = 'EDIT_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',
  CHANGE_ROLE_STATUS = 'CHANGE_ROLE_STATUS',

  CARD_MANAGEMENT = "CARD_MANAGEMENT",
  VIEW_CARD_DETAILS = "VIEW_CARD_DETAILS",
  UPDATE_CARD = "UPDATE_CARD",
  ACTIVATE_CARD = "ACTIVATE_CARD",
  CANCEL_CARD = "CANCEL_CARD",
  SUSPEND_CARD = "SUSPEND_CARD",
  REISSUE_CARD = "REISSUE_CARD",
  ADD_CARD = "ADD_CARD",

  MANAGE_REQUESTS = "MANAGE_REQUESTS",
  VIEW_REQUEST_DETAILS = "VIEW_REQUEST_DETAILS",
  CREATE_NEW_REQUEST = "CREATE_NEW_REQUEST",

//printing request authorities
  PRINTING_REQUEST_MANAGEMENT = "PRINTING_REQUEST_MANAGEMENT",
  VIEW_PRINTING_REQUEST_DETAILS = "VIEW_PRINTING_REQUEST_DETAILS",
  ADD_PRINTING_REQUEST = "ADD_PRINTING_REQUEST"


}
