export enum CardStatus {
  READY_TO_PRINT = 'READY_TO_PRINT',
  SENT_FOR_PRINT = 'SENT_FOR_PRINT',
  PRINTED = 'PRINTED',
  DISTRIBUTED = 'DISTRIBUTED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED',
  WAITING_TO_SEND = 'WAITING_TO_SEND',
  EXPIRED = 'EXPIRED'
}
