
export enum CardStatusActions {
  ACTIVATE_CARD = 'ACTIVATE_CARD',
  SUSPEND_CARD = 'SUSPEND_CARD',
  CANCEL_CARD = 'CANCEL_CARD',
  REISSUE_CARD = 'REISSUE_CARD',
  REPRINT_CARD = 'REPRINT_CARD',
}
