export enum PrintRequestStatus {
  NEW= "NEW",
  CONFIRMED = "CONFIRMED",
  UNDER_PROCESSING = "UNDER_PROCESSING",
  PROCESSED = "PROCESSED",
  SENT_TO_PRINTING = "SENT_TO_PRINTING",
  CANCELLED = "CANCELLED"
}
