USE MASTER
GO
CREATE LOGIN "shc_user" WITH PASSWORD=N'Aa123456789', DEFAULT_DATABASE="shc_portal", DEFAULT_LANGUAGE=US_ENGLISH
GO
ALTER LOGIN "shc_user" ENABLE
GO

USE shc_portal
GO
CREATE USER "shc_user" FOR LOGIN "shc_user" WITH DEFAULT_SCHEMA="shc_portal"
GO
ALTER ROLE [db_owner] ADD MEMBER [shc_user]
GO
