USE shc_portal
GO

drop table if exists shc_portal.shc_group_applicant_list;
drop table if exists shc_portal.shc_company_staff_title_lk;
drop table if exists shc_portal.shc_company_ritual_step;
drop table if exists shc_portal.shc_applicant_group;
drop table if exists shc_portal.shc_company_season_package;
drop table if exists shc_portal.shc_company_staff;
drop table if exists shc_portal.shc_applicant_package_housing;
drop table if exists shc_portal.shc_package_housing;
drop table if exists shc_portal.shc_applicant_package_catering;
drop table if exists shc_portal.shc_applicant_package_transportation;
alter table shc_portal.shc_applicant_ritual drop constraint fk_shc_applicant_ritual_applicant_package;
drop table if exists shc_portal.shc_applicant_package;
drop table if exists shc_portal.shc_ritual_package;
drop table if exists shc_portal.shc_company_ritual_season;
drop table if exists shc_portal.shc_company;
drop table if exists shc_portal.shc_ritual_season;
drop table if exists shc_portal.shc_package_transportation;
drop table if exists shc_portal.shc_package_catering;
drop table if exists shc_portal.shc_ritual_package;
drop table if exists shc_portal.shc_package_type_lk;
drop table if exists shc_portal.shc_housing_zone;
drop table if exists shc_portal.shc_housing_category_lk;
drop table if exists shc_portal.shc_housing_type_lk;
drop table if exists shc_portal.shc_transportation_type_lk;
drop table if exists shc_portal.shc_applicant_group_type_lk;
drop table if exists shc_portal.shc_company_ritual_step_lk;
drop table if exists shc_portal.shc_housing_site_lk;
drop table if exists shc_portal.shc_applicant_digital_id_status_lk;
drop table if exists shc_portal.shc_user_notification_category_preference;
drop table if exists shc_portal.shc_religious_occasions_day_lk;
drop table if exists shc_portal.shc_meal_type_lk;
drop table if exists shc_portal.shc_user_card_status_audit;
drop table if exists shc_portal.shc_ritual_group;
drop table if exists shc_portal.shc_ritual_zone;
drop table if exists shc_portal.shc_ritual_unit;
drop table if exists shc_portal.shc_user_notification;
drop table if exists shc_portal.shc_user_notification_status_lk;
drop table if exists shc_portal.shc_notification_request_parameter_value;
drop table if exists shc_portal.shc_notification_template_parameter;
drop table if exists shc_portal.shc_notification_request;
drop table if exists shc_portal.shc_notification_template_content;
drop table if exists shc_portal.shc_notification_template;
drop table if exists shc_portal.shc_notification_category_lk;
drop table if exists shc_portal.shc_notification_template_type_lk;
drop table if exists shc_portal.shc_notification_template_status_lk;
drop table if exists shc_portal.shc_notification_processing_status_lk;
drop table if exists shc_portal.shc_notification_template_name_lk;
drop table if exists shc_portal.shc_user_card_status_audit;
drop table if exists shc_portal.shc_incident_attachment;
drop table if exists shc_portal.shc_applicant_incident;
drop table if exists shc_portal.shc_incident_type_lk;
drop table if exists shc_portal.shc_incident_status_lk;
GO
